# For remote theme (GitHub Pages compatible):
theme: minima
title: "Jan Sneeuw"
author: "Jan Sneeuw"

lang: en

minima:
  social_links:
    - title: Jekyll repository at GitHub
      icon: github
      url: "https://github.com/jekyll/jekyll"
    - title: Jekyll at X (formerly Twitter)
      icon: x-twitter
      url: "https://x.com/jekyllrb"

sass:
  sass_dir: assets/css
  style: compressed

# Enable plugins if needed
plugins:
  - jekyll-feed

google_analytics: G-E9H2BVCG3H

















