# For remote theme (GitHub Pages compatible):
theme: jekyll-theme-hacker
title: "Jan Sneeuw"
author: "Jan Sneeuw"

header_pages:
  - index.md
  - posts.md
  - papers.md
  - pictures.md

# Enable plugins if needed
plugins:
  - jekyll-feed




