# For remote theme (GitHub Pages compatible):
theme: minima
title: "Jan Sneeuw"
author: "Jan Sneeuw"

lang: en

#minima:
#skin: dark

#header_pages:
#  - index.md
#  - posts.md
#  - papers.md
#  - pictures.md

sass:
  sass_dir: assets/css
  style: compressed

# Enable plugins if needed
plugins:
  - jekyll-feed














