# For remote theme (GitHub Pages compatible):
remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme
title: "Jan Sneeuw"
author: "Jan Sneeuw"

header_pages:
  - index.md
  - posts.md
  - papers.md
  - pictures.md

# Enable plugins if needed
plugins:
  - jekyll-feed



